### ISSUE TITLE
Aggregating data from yaml files so that people can one little yaml with their profile

### ISSUE THREAD

**Issue by jurra** [osc-delft/osc-delft.github.io#23]
**Potential problem**
One yaml files become bigger they can become more error prone. People can easily make mistakes in yaml.

**Manual solution**
1. Let people open an issue using a metadata template that then the repo owner can add to the aggregate. 👍 
2. Ask people to push their profile in a small yaml file in a folder, and then the owner of the repo, can add it to the big list. 
3. Let people do pull request directly on the data file :-1 Not everyone feels confident in doing a pull request, although it can be fun to learn how git works :) If this is a goal then we just need to double check the change. 

**Automated solution**
For the context of many people updating their profile, it might be better to ask them to put their little yaml profile in a folder, validate it, and then aggregate it to a bigger yaml file or json file. So we could automate the generation of the current manually written yaml file.

**Comment by jurra** [comment]
Example of a metadata template that can be turned into an issue template:

```yaml
Firsnamet-Lastname:
  first-name: FirstName
  last-name: LastName
  photo: url   
  position: Assistant Professor
  faculty: Faculty of Aerospace Engineering
  department: Aerodynamics, Wind Energy, Flight Performance and Propulsion
  email: jasdsa@tudelf.tnl
  website: mywebsite.org
  orcid: 0000-9834-000-1231
  github: username
  expertise: open source, dancing, playing tennis, 
```
